name: Update Submodules in Child Repo

on:
  workflow_dispatch:
  repository_dispatch:
    types: [external-push]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Parent Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive  # This ensures all submodules are checked out
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      - name: Update Submodules
        run: |
          echo "Updating all submodules..."
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git submodule update --init --recursive
          git add .
          git commit -m "updating all submodules"
          git push

