name: Update Submodules

on:
  workflow_dispatch:
  repository_dispatch:
    types: [external-push]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with Nested Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      - name: Initialize and Update Submodules
        run: |
          echo "Initializing and updating submodules..."
          git submodule update --init --recursive
          git submodule status # Check the status of submodules

      - name: Ensure Submodule is on Correct Branch
        run: |
          echo "Ensuring submodule is on the correct branch..."
          git submodule foreach 'git checkout main || git checkout -b main'
          git submodule foreach 'git pull origin main' # Fetch and update the submodule

      - name: Fetch and Merge Submodules
        run: |
          echo "Fetching and merging submodules..."
          git submodule foreach 'git fetch origin main; git merge origin/main || echo "Merge failed for $name"'

      - name: Commit Submodule Changes
        run: |
          echo "Checking for submodule changes..."
          git add .
          git diff --cached # Debugging: Check what has changed
          git commit -m "Updated submodules" || echo "No changes to commit"

      - name: Push Changes
        run: |
          echo "Pushing changes to origin..."
          git push origin main || echo "Push failed"
