name: Update Submodules

on:
  push:
    branches:
      - main
    paths:
      - 'Auth/**'
      - 'Superior Backend/**'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Submodules
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Auto-update submodule references" || echo "No changes to commit"
          git push origin main
