name: Update Submodules

on:
  workflow_dispatch:
  repository_dispatch:
    types: [external-push]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with Nested Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true
      - name: Update All Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive git fetch origin main
          git submodule foreach --recursive git merge origin/main || true
          git add .
          git commit -m "Updated submodules" || echo "No changes to commit"
          git push origin main

