name: Update Submodules

on:
  push:
    branches:
      - main
    paths:
      - 'Auth/**'
      - 'Superior Backend/**'
      - 'Dashboard/**'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with Nested Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Update All Submodules
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Auto-update submodule references" || echo "No changes to commit"
          git push origin main
