name: Update Submodules

on:
  workflow_dispatch:
  repository_dispatch:
    types: [external-push]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with Nested Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      - name: Update All Submodules
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Updated submodule references from unparallel-dev" || echo "No changes to commit"
          git push origin main
